hieutran_user:
    resource: "@HieutranUserBundle/Resources/config/routing.yml"
    prefix:   /

hieutran_backend:
    type:   rest
    resource: "@HieutranBackendBundle/Resources/config/routing.yml"
    prefix:   /admin